#: kivy 1.9.1

<LeftButton>:
    background_normal: 'sprites/left_btn1.png'
    background_down: 'sprites/left_btn2.png'
    border: 0,0,0,0

<RightButton>:
    background_normal: 'sprites/right_btn1.png'
    background_down: 'sprites/right_btn2.png'
    border: 0,0,0,0

<PaceSlider>:
    cursor_image: 'sprites/pace.png'
    cursor_height: 24
    cursor_width: 50
    
<StrideSlider>:
    cursor_image: 'sprites/stride.png'
    cursor_height: 30
    cursor_width: 50